network_proxy_node:
  ros__parameters:
    delay_sec: 0.0
    packet_loss_rate: 0.0
    noise_stddev: 0.0
    proxy_configs:
      - "/robot1/local_map,/proxy/robot1/local_map,sensor_msgs/msg/PointCloud2"
      - "/robot2/local_map,/proxy/robot2/local_map,sensor_msgs/msg/PointCloud2"
      - "/robot1/pose_update,/proxy/robot1/pose_update,nav_msgs/msg/Odometry"
      - "/robot2/pose_update,/proxy/robot2/pose_update,nav_msgs/msg/Odometry"
      - "/map_fusion/inter_robot_constraints,/proxy/map_fusion/inter_robot_constraints,geometry_msgs/msg/PoseStamped"
