#!/usr/bin/env python3
import rclpy
from rclpy.node import Node
from geometry_msgs.msg import PoseStamped
from nav_msgs.msg import OccupancyGrid
import random

class DynamicTaskAllocationNode(Node):
    def __init__(self):
        super().__init__('dynamic_task_allocation_node')

        # Subscribe to the global map generated by Global Map Fusion
        self.global_map_sub = self.create_subscription(
            OccupancyGrid,
            '/emrmf/global_map',
            self.global_map_callback,
            10
        )

        # Publisher for goal poses for individual robots based on task allocation
        self.robot1_goal_pub = self.create_publisher(
            PoseStamped,
            '/robot_1/goal_pose',
            10
        )

        self.robot2_goal_pub = self.create_publisher(
            PoseStamped,
            '/robot_2/goal_pose',
            10
        )

        self.get_logger().info("Dynamic Task Allocation Node Initialized. Awaiting global map.")

    def calculate_exploration_cost(self, map_data):
        """
        Placeholder for minimizing exploration cost (Phase 3 task partitioning).
        This function identifies unexplored regions and assigns them based on the robot's current pose.
        """
        # Mock calculation: Generate random goal coordinates to simulate partitioning
        self.get_logger().info("Computing exploration cost and identifying unmapped frontiers...")
        return {
            'robot1': (random.uniform(-5.0, 5.0), random.uniform(-5.0, 5.0)),
            'robot2': (random.uniform(5.0, 15.0), random.uniform(-5.0, 5.0))
        }

    def generate_goal_pose(self, coordinates):
        """Helper to create a PoseStamped message from (x, y) coordinates"""
        pose = PoseStamped()
        pose.header.frame_id = "map"
        pose.header.stamp = self.get_clock().now().to_msg()
        pose.pose.position.x = coordinates[0]
        pose.pose.position.y = coordinates[1]
        pose.pose.orientation.w = 1.0 # default heading
        return pose

    def global_map_callback(self, msg):
        self.get_logger().info("Received updated global map. Partitioning tasks...")

        # Determine optimal next locations for each robot based on map
        frontiers = self.calculate_exploration_cost(msg)

        goal_1 = self.generate_goal_pose(frontiers['robot1'])
        goal_2 = self.generate_goal_pose(frontiers['robot2'])

        # Publish goals to navigate the robots to their assigned regions
        self.robot1_goal_pub.publish(goal_1)
        self.robot2_goal_pub.publish(goal_2)

        self.get_logger().info(f"Published task allocations. Robot 1 goal: ({goal_1.pose.position.x:.2f}, {goal_1.pose.position.y:.2f})")
        self.get_logger().info(f"Robot 2 goal: ({goal_2.pose.position.x:.2f}, {goal_2.pose.position.y:.2f})")

def main(args=None):
    rclpy.init(args=args)
    task_allocation_node = DynamicTaskAllocationNode()
    try:
        rclpy.spin(task_allocation_node)
    except KeyboardInterrupt:
        pass
    finally:
        task_allocation_node.destroy_node()
        rclpy.shutdown()

if __name__ == '__main__':
    main()
