#!/usr/bin/env python3
import rclpy
from rclpy.node import Node
from nav_msgs.msg import Odometry
import time

class LoRaTransmitterNode(Node):
    def __init__(self):
        super().__init__('lora_transmitter_node')

        # Subscribe to the trusted pose generated by the Trust Factor Node
        self.subscription = self.create_subscription(
            Odometry,
            '/emrmf/trusted_pose',
            self.listener_callback,
            10
        )
        self.subscription  # prevent unused variable warning

        self.declare_parameter('port', '/dev/ttyUSB0')
        self.declare_parameter('baudrate', 115200)

        self.port = self.get_parameter('port').get_parameter_value().string_value
        self.baudrate = self.get_parameter('baudrate').get_parameter_value().integer_value

        self.get_logger().info(f"LoRa Transmitter initialized on {self.port} at {self.baudrate} baud.")

    def listener_callback(self, msg):
        """
        Placeholder for sending data via LoRa serial communication.
        In a real implementation, you would serialize the Odometry or
        RTAB-Map map data and write it to the serial port.
        """

        # Simulate temporal decay: log timestamp for transmission
        transmission_time = time.time()

        x = msg.pose.pose.position.x
        y = msg.pose.pose.position.y
        z = msg.pose.pose.position.z

        self.get_logger().info(f"Transmitting via LoRa: Pose ({x:.2f}, {y:.2f}, {z:.2f}) at timestamp {transmission_time:.2f}")

def main(args=None):
    rclpy.init(args=args)
    lora_transmitter_node = LoRaTransmitterNode()
    try:
        rclpy.spin(lora_transmitter_node)
    except KeyboardInterrupt:
        pass
    finally:
        lora_transmitter_node.destroy_node()
        rclpy.shutdown()

if __name__ == '__main__':
    main()
